# Generated by Django 3.1 on 2020-10-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_business_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Enter your M-PESA mobile number'),
        ),
    ]
