# Generated by Django 3.1 on 2020-10-24 08:46

from django.db import migrations
from django.apps.registry import apps


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20201023_1941'),
    ]

    def create_plans(self, schema_editor):
        Plan = apps.get_model('membership', 'Plan')
        Plan.objects.create(name='Free', description='Free plan')

    operations = [
        migrations.RunPython(
            create_plans,
            migrations.RunPython.noop
        ),
    ]
