# Generated by Django 3.1 on 2020-11-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_create_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
