# Generated by Django 3.1 on 2020-11-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20201104_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='ends_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_time',
            field=models.DateField(),
        ),
    ]
