# Generated by Django 3.1 on 2020-10-15 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20201015_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
