# Generated by Django 3.1 on 2020-11-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20201104_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='ends_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
