# Generated by Django 3.1 on 2020-11-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_auto_20201107_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
